[build]
  publish = "publish"
  functions = "functions-zip"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr?slug=:splat"
  status = 200

[[headers]]
  for = "/storefront.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/storefront.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/storefront.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/checkout.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/checkout.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/chunk.*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=60, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=600"
[[redirects]]
from = “/xilofone-para-treinamento-auditivo-kit-20-tons-c6-a-c7/”
to = “/kit-xilofone-para-aperfeicoamento-auditivo/”
status = 301
force=true
[[redirects]]
from = “/xylo-tongs”
to = “/diversos”
status = 301
force=true
[[redirects]]
from = “/barras-sonoras/”
to = “/metalofones/”
status = 301
force=true
[[redirects]]
from = “/pages/catalogo/”
to = “/pages/catalogos-e-precos/”
status = 301
force=true
