[build]
  publish = "publish"
  functions = "functions-zip"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr?slug=:splat"
  status = 200

[[headers]]
  for = "/storefront.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/storefront.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/storefront.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/checkout.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/checkout.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/chunk.*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=60, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=600"
    [[redirects]]
from = “/kalimba-de-madeira-09-laminas/”
to = “/kalimba-de-madeira-09-lamelas/”
status = 301
force=true
[[redirects]]
from = “/kalimba-em-coco-09-laminas/”
to = “/kalimba-em-coco-09-lamelas/”
status = 301
force=true
[[redirects]]
from = “/mini-clavas-ipe-especial/”
to = “/mini-claves-ipe-especial/”
status = 301
force=true
[[redirects]]
from = “/mini-clavas-bit-ton/”
to = “/mini-claves-bit-ton/”
status = 301
force=true
[[redirects]]
from = “/kalimba-mini-em-coco-05-laminas/”
to = “/kalimba-mini-em-coco-05-lamelas/”
status = 301
force=true
[[redirects]]
from = “/kalimba-de-madeira-07-laminas/”
to = “/kalimba-em-madeira-07-lamelas/”
status = 301
force=true
[[redirects]]
from = “/kalimba-mini-em-madeira-05-laminas/”
to = “/kalimba-mini-em-madeira-05-lamelas/”
status = 301
force=true
[[redirects]]
from = “/kalimba-09-laminas-madeira-especial/”
to = “/kalimba-09-lamelas-madeira-especial/”
status = 301
force=true
[[redirects]]
from = “/kalimba-07-laminas-madeira-especial/”
to = “/kalimba-07-lamelas-madeira-especial/”
status = 301
force=true
[[redirects]]
from = “/kalimba-de-madeira-09-lamelas/”
to = “/kalimba-em-madeira-09-lamelas/”
status = 301
force=true
[[redirects]]
from = “/xilofone-para-treinamento-auditivo-kit-20-tons-c6-a-c7/”
to = “/kit-xilofone-para-aperfeicoamento-auditivo/”
status = 301
force=true
